### ISSUE TITLE
Problem compiling onto Linux machine

### ISSUE THREAD

**Issue by slarge** [flr/FLAssess#3]
It seems that the source package from github devtools::install_github("flr/FLAssess") also provides the binary. The build command doesn't find anything and tries to install the binary library, which contains a broken reference: 

$ strings -a FLAssess.so | grep \/home
/home/mosquia/R/x86_64-pc-linux-gnu-library/3.3/FLash/libs//FLash.so

Warning: namespace ‘FLAssess’ is not available and has been replaced
by .GlobalEnv when processing object ‘nhke’
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/local/lib/R/site-library/FLAssess/libs/FLAssess.so':
  /home/mosquia/R/x86_64-pc-linux-gnu-library/3.3/FLash/libs//FLash.so: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/FLAssess’
Error: Command failed (1)

**Comment by iagomosqueira** [comment]
Thanks for the warning. I have deleted them and now github is clean. Notice that this package has not changed for a long time, so installing from github or the repository should make no difference.

Let me know if it works for you.

**Comment by slarge** [comment]
Works like a charm. Thanks!
